server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /drivers {
        proxy_pass http://driver-stats-service;
    }

    location /races {
        proxy_pass http://race-stats-service;
    }

    location /teams {
        proxy_pass http://team-stats-service;
    }
}
