# ============================================
# DRIVER STATS SERVICE — Deployment
# ============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-stats-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-stats
  template:
    metadata:
      labels:
        app: driver-stats
    spec:
      serviceAccountName: driver-stats-sa
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.96.0.10
          - 8.8.8.8
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      containers:
        - name: driver-stats-container
          image: aminedelim/driver-stats-service:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3001

---
# ============================================
# DRIVER STATS SERVICE — Service
# ============================================
apiVersion: v1
kind: Service
metadata:
  name: driver-stats-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3001
  selector:
    app: driver-stats

---
# ============================================
# RACE STATS SERVICE — Deployment
# ============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: race-stats-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: race-stats
  template:
    metadata:
      labels:
        app: race-stats
    spec:
      serviceAccountName: race-stats-sa
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.96.0.10
          - 8.8.8.8
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      containers:
        - name: race-stats-container
          image: aminedelim/race-stats-service:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3002

---
# ============================================
# RACE STATS SERVICE — Service
# ============================================
apiVersion: v1
kind: Service
metadata:
  name: race-stats-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3002
  selector:
    app: race-stats

---
# ============================================
# TEAM STATS SERVICE — Deployment
# ============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-stats-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-stats
  template:
    metadata:
      labels:
        app: team-stats
    spec:
      serviceAccountName: team-stats-sa
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.96.0.10
          - 8.8.8.8
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      containers:
        - name: team-stats-container
          image: aminedelim/team-stats-service:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3003

---
# ============================================
# TEAM STATS SERVICE — Service
# ============================================
apiVersion: v1
kind: Service
metadata:
  name: team-stats-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3003
  selector:
    app: team-stats

---
# ============================================
# FRONTEND — Deployment
# ============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.96.0.10
          - 8.8.8.8
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      containers:
        - name: frontend-container
          image: aminedelim/f1-frontend:1
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
# ============================================
# FRONTEND — Service
# ============================================
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: frontend

---
# ============================================
# INGRESS — Gateway unique
# ============================================
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: f1-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: f1.local
      http:
        paths:
          - path: /drivers
            pathType: Prefix
            backend:
              service:
                name: driver-stats-service
                port:
                  number: 80
          - path: /races
            pathType: Prefix
            backend:
              service:
                name: race-stats-service
                port:
                  number: 80
          - path: /teams
            pathType: Prefix
            backend:
              service:
                name: team-stats-service
                port:
                  number: 80
          - path: /favorites
            pathType: Prefix
            backend:
              service:
                name: favorites-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
---
# ============================================
# POSTGRESQL — PersistentVolumeClaim
# ============================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi

---
# ============================================
# POSTGRESQL — Deployment
# ============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-container
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: f1db
            - name: POSTGRES_USER
              value: f1user
            - name: POSTGRES_PASSWORD
              value: f1password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
# ============================================
# POSTGRESQL — Service
# ============================================
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres

---
# ============================================
# FAVORITES SERVICE — Deployment
# ============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: favorites-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favorites
  template:
    metadata:
      labels:
        app: favorites
    spec:
      serviceAccountName: favorites-sa
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.96.0.10
          - 8.8.8.8
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      containers:
        - name: favorites-container
          image: aminedelim/favorites-service:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3004
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_NAME
              value: f1db
            - name: DB_USER
              value: f1user
            - name: DB_PASSWORD
              value: f1password

---
# ============================================
# FAVORITES SERVICE — Service
# ============================================
apiVersion: v1
kind: Service
metadata:
  name: favorites-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3004
  selector:
    app: favorites
